package com.cardio_generator.outputs;

import java.io.IOException;

/**
 * The OutputStrategy interface defines a unified approach for outputting data generated by different
 * data generators in the system.
 *
 */
public interface OutputStrategy {

    /**
     * This method is responsible for handling the output logic
     *
     * @param patientId The identifier for the patient to whom the data belongs. This ID ensures that
     *                  data can be correctly associated with its respective patient in the output.
     * @param timestamp The timestamp at which the data was generated, representing when the data was recorded
     *                  or observed. This is crucial for maintaining the chronological integrity of the data.
     * @param label The label that describes the data
     * @param data The patient data to be written into a file then stored in the directory
     */
    void output(int patientId, long timestamp, String label, String data) throws IOException;
}

